Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "debian/jessie64"
    master.vm.hostname = 'master'
    master.vm.synced_folder '.\mount', '/vagrant'
    master.vm.provision "shell", path: "presetup.sh"
    #master.vm.provision "shell", path: "master.sh"
    master.vm.network "private_network", ip: "192.168.50.10",
      virtualbox__intnet: true

    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1512]
      v.customize ["modifyvm", :id, "--name", "chef-master"]
    end
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "debian/jessie64"
    node1.vm.hostname = 'node1'
    node1.vm.synced_folder ".", "/vagrant", disabled: true
    node1.vm.provision "shell", path: "presetup.sh"
    node1.vm.provision "shell", path: "node.sh"
    node1.vm.network "private_network", ip: "192.168.50.11",
      virtualbox__intnet: true

    node1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node1"]
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "debian/jessie64"
    node2.vm.hostname = 'node2'
    node2.vm.synced_folder ".", "/vagrant", disabled: true
    node2.vm.provision "shell", path: "presetup.sh"
    node2.vm.provision "shell", path: "node.sh"
    node2.vm.network "private_network", ip: "192.168.50.12",
      virtualbox__intnet: true

    node2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node2"]
    end
  end
end