Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box = "debian/stretch64"
      master.vm.hostname = 'gitlab'
      master.vm.provision "shell", path: "server.sh"
      master.vm.network "forwarded_port", guest: 80, host: 81
  
      master.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "gitlab"]
      end
    end
  end