Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "hadoop#{i}" do |node|
      node.vm.box = "debian/contrib-jessie64"
      node.vm.hostname = "hadoop#{i}"
      node.vm.synced_folder '.\mount', '/hadoop_src'
      node.vm.provision "shell", path: "presetup.sh"
      node.vm.network "private_network", ip: "192.168.50.10#{i}",
        virtualbox__intnet: true
      node.vm.provider :virtualbox do |v|
        v.customize  ["modifyvm", :id, "--memory", 1000]
        v.customize ["modifyvm", :id, "--name", "hadoop#{i}"]
      end
    end
  end
end
