Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box = "debian/stretch64"
      master.vm.hostname = 'master'
      master.vm.provision "shell", path: "server.sh"
      #master.vm.network "public_network", ip: "10.10.10.1"
      #master.vm.network :public_network
      master.vm.network "forwarded_port", guest: 8080, host: 8080
  
      master.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 1512]
        v.customize ["modifyvm", :id, "--name", "chef-master"]
      end
    end
  end